create table learning_materials (material_id binary(16) not null, description varchar(255), file_id binary(16), name varchar(255), teaching_phase_id binary(16) not null, primary key (material_id)) engine=InnoDB;
create table lessons (lesson_id binary(16) not null, learning_prerequisites varchar(1024), license varchar(255), prior_knowledge varchar(512), schedule varchar(255), subject varchar(255), target_audience varchar(255), thematic_areas varchar(512), topic varchar(255), primary key (lesson_id)) engine=InnoDB;
create table teaching_units (teaching_unit_id binary(16) not null, acquired_competences varchar(1024), didactic_considerations varchar(4048), rough_content_analysis varchar(4048), topic varchar(255), curriculum_alignment varchar(4048), framework_conditions varchar(512), instruction_methods varchar(255), lesson_id binary(16) not null, primary key (teaching_unit_id)) engine=InnoDB;
create table teaching_phase (teaching_phase_id binary(16) not null, phase tinyint, time_frame decimal(21,0), topic varchar(255), teaching_unit_id binary(16) not null, primary key (teaching_phase_id)) engine=InnoDB;
create table uploaded_files (file_id binary(16) not null, data longblob, name varchar(255), type varchar(255), primary key (file_id)) engine=InnoDB;
create table building_block_properties (building_block_id binary(16) not null, display_name varchar(255), `key` varchar(255), `order` integer, type tinyint, description varchar(255)) engine=InnoDB;
create table building_blocks (building_block_id binary(16) not null, description varchar(255), technology varchar(255), name varchar(50) not null, release_status tinyint, primary key (building_block_id)) engine=InnoDB;
create table comments (comment_id binary(16) not null, content varchar(255), created_at datetime(6), user_id varchar(255), discussion_id binary(16) not null, primary key (comment_id)) engine=InnoDB;
create table course_notes (course_id binary(16) not null, content tinyblob, primary key (course_id)) engine=InnoDB;
create table courses (course_id binary(16) not null, lesson_id binary(16), user_id varchar(255), technology_wish varchar(255), primary key (course_id)) engine=InnoDB;
create table discussion_references (dtype varchar(31) not null, discussion_reference_id binary(16) not null, course_id binary(16), mockup_id binary(16), page_id binary(16), discussion_id binary(16) not null, primary key (discussion_reference_id)) engine=InnoDB;
create table discussions (discussion_id binary(16) not null, user_id varchar(255), resolved_at datetime(6), state tinyint, title varchar(255), primary key (discussion_id)) engine=InnoDB;
create table mockups (mockup_id binary(16) not null, page_id binary(16), created_by varchar(255), description varchar(255), file_id binary(16) not null, primary key (mockup_id)) engine=InnoDB;
create table page_building_blocks (page_building_block_id binary(16) not null, building_block_id binary(16) not null, page_id binary(16) not null, primary key (page_building_block_id)) engine=InnoDB;
create table page_links (surrogate_id binary(16) not null, page_id binary(16), target_page_id binary(16), primary key (surrogate_id)) engine=InnoDB;
create table pages (page_id binary(16) not null, teaching_phase_id binary(16), title varchar(255), course_id binary(16) not null, primary key (page_id)) engine=InnoDB;

alter table learning_materials add constraint FKlfnptvdqtmtjdkynpcywmm2oc foreign key (teaching_phase_id) references teaching_phase (teaching_phase_id);
alter table teaching_units add constraint FKr99iraf7u7g25ve2n7lxluxft foreign key (lesson_id) references lessons (lesson_id);
alter table teaching_phase add constraint FKbst13auefhu6ias79t614fvd1 foreign key (teaching_unit_id) references teaching_units (teaching_unit_id);
alter table mockups add constraint UK_7xfahx7h8c752nmke5lxbk44o unique (file_id);
alter table mockups add constraint FK21ombn8gmxdu00gfdbkuljjvd foreign key (file_id) references uploaded_files (file_id);
alter table building_block_properties add constraint FKsa46ycrttslf80o4rxs1pfiy3 foreign key (building_block_id) references building_blocks (building_block_id);
alter table comments add constraint FKrwtnj1erhxne1g36nbfk5hdfi foreign key (discussion_id) references discussions (discussion_id);
alter table discussion_references add constraint FKlhoearuw0u1qnakt0kas9qbpx foreign key (discussion_id) references discussions (discussion_id);
alter table page_building_blocks add constraint FKepc9fkt6pcsjh33o9dcdf5j1a foreign key (page_id) references pages (page_id);
alter table pages add constraint FK27amb80l7p6789ia2yrt1bfmm foreign key (course_id) references courses (course_id);