create table building_block_mockups (mockup_id binary(16) not null, building_block_id binary(16) not null, created_by varchar(255), description text, file_id binary(16), primary key (mockup_id)) engine=InnoDB;
create table building_block_properties (building_block_id binary(16) not null, key_name varchar(255) not null, description text, display_name varchar(255), order_index bigint, type tinyint check (type between 0 and 0), primary key (building_block_id, key_name)) engine=InnoDB;
create table building_blocks (building_block_id binary(16) not null, description text, name varchar(50) not null, release_status tinyint check (release_status between 0 and 1), technology varchar(255), primary key (building_block_id)) engine=InnoDB;
create table comments (comment_id binary(16) not null, content text, created_at datetime(6), user_id varchar(255), discussion_id binary(16) not null, primary key (comment_id)) engine=InnoDB;
create table course_notes (course_id binary(16) not null, content mediumtext, primary key (course_id)) engine=InnoDB;
create table courses (course_id binary(16) not null, lesson_id binary(16), user_id varchar(255), technology_wish varchar(255), primary key (course_id)) engine=InnoDB;
create table discussion_references (dtype varchar(31) not null, discussion_reference_id binary(16) not null, building_block_id binary(16) not null, mockup_id binary(16), page_id binary(16), discussion_id binary(16) not null, primary key (discussion_reference_id)) engine=InnoDB;
create table discussions (discussion_id binary(16) not null, user_id varchar(255), resolved_at datetime(6), state tinyint check (state between 0 and 1), title varchar(255), primary key (discussion_id)) engine=InnoDB;
create table learning_materials (material_id binary(16) not null, description text, file_id binary(16), name varchar(255), teaching_phase_id binary(16) not null, primary key (material_id)) engine=InnoDB;
create table lessons (lesson_id binary(16) not null, learning_prerequisites text, license varchar(255), prior_knowledge text, schedule varchar(255), subject varchar(255), target_audience varchar(255), thematic_areas text, topic text, primary key (lesson_id)) engine=InnoDB;
create table mockups (mockup_id binary(16) not null, created_by varchar(255), description text, file_id binary(16), page_id binary(16), primary key (mockup_id)) engine=InnoDB;
create table page_building_block_property_values (key_name varchar(255) not null, page_building_block_id binary(16) not null, property_value varchar(255), primary key (key_name, page_building_block_id)) engine=InnoDB;
create table page_building_blocks (page_building_block_id binary(16) not null, building_block_id binary(16) not null, order_index bigint, page_id binary(16) not null, primary key (page_building_block_id)) engine=InnoDB;
create table page_links (surrogate_id binary(16) not null, condition_value varchar(512), page_id binary(16), target_page_id binary(16), primary key (surrogate_id)) engine=InnoDB;
create table pages (page_id binary(16) not null, implementation_status tinyint check (implementation_status between 0 and 3), notes mediumtext, order_index bigint, teaching_phase_id binary(16), title varchar(255), course_id binary(16) not null, primary key (page_id)) engine=InnoDB;
create table readme (building_block_id binary(16) not null, content tinyblob, primary key (building_block_id)) engine=InnoDB;
create table teaching_units (teaching_unit_id binary(16) not null, acquired_competences mediumtext, curriculum_alignment mediumtext, didactic_considerations mediumtext, framework_conditions text, instruction_methods text, order_index bigint, rough_content_analysis mediumtext, topic text, lesson_id binary(16) not null, primary key (teaching_unit_id)) engine=InnoDB;
create table teaching_phase (teaching_phase_id binary(16) not null, order_index bigint, phase tinyint check (phase between 0 and 5), teacher_presence tinyint check (teacher_presence between 0 and 2), time_frame decimal(21,0), topic text, teaching_unit_id binary(16) not null, primary key (teaching_phase_id)) engine=InnoDB;
create table uploaded_files (file_id binary(16) not null, data tinyblob, name varchar(255), type varchar(255), primary key (file_id)) engine=InnoDB;
create table users (user_id varchar(255) not null, first_name varchar(255), last_name varchar(255), primary key (user_id)) engine=InnoDB;

alter table building_block_properties add constraint FK3r91e03qlws90pxkbg2x6ffe2 foreign key (building_block_id) references building_blocks (building_block_id);
alter table comments add constraint FK40i4dao9h6hd08g5wmmw87lnj foreign key (discussion_id) references discussions (discussion_id);
alter table discussion_references add constraint FKrvkmuqc4k741h4rl4d1okp9cm foreign key (discussion_id) references discussions (discussion_id);
alter table learning_materials add constraint FK65igiy6baubqwpooauwix3anr foreign key (teaching_phase_id) references teaching_phase (teaching_phase_id);
alter table page_building_blocks add constraint FKk1r8etby59lxv18vbwa6sdve0 foreign key (page_id) references pages (page_id);
alter table pages add constraint FKe5kvrj8x9g1xfakh692bb9u4b foreign key (course_id) references courses (course_id);
alter table teaching_units add constraint FK91rlodv1fc0vhlhgkt58mascl foreign key (lesson_id) references lessons (lesson_id);
alter table teaching_phase add constraint FKhryx9xub3467hfiqx4560wsyc foreign key (teaching_unit_id) references teaching_units (teaching_unit_id);
