server:
  port: ${PORT:8500}
auth0:
  audience: ${AUTH0_AUDIENCE:https://elst.de/api/}
spring:
  application:
    name: elst
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URL:https://elst.eu.auth0.com/}
  flyway:
    enabled: true
    default-schema: elst
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost:3306}/${SCHEMA:elst}?rewriteBatchedStatements=true
    username: ${DB_USERNAME:elst}
    password: ${DB_PASSWORD:elst-pw}
  modulith:
    moments:
      enable-time-machine: false
      locale: de_DE
  mustache:
    enabled: false
    check-template-location: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
logging:
  level:
    root: INFO