---
servers:
- url: "http://localhost:8080"
openapi: "3.0.3"
security:
    - bearerAuth: []
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
paths:
  /lessons/{lessonId}/teaching-units/order:
    $ref: "./openapi-lessons.yaml#/paths/~1lessons~1{lessonId}~1teaching-units~1order"
  /building-block-mockups/{mockupId}:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-block-mockups~1{mockupId}"
  /page-links:
    $ref: "./openapi-courses.yaml#/paths/~1page-links"
  /teaching-phases/{teachingPhaseId}:
    $ref: "./openapi-lessons.yaml#/paths/~1teaching-phases~1{teachingPhaseId}"
  /discussions/{discussionId}/comments:
    $ref: "./openapi-discussion.yaml#/paths/~1discussions~1{discussionId}~1comments"
  /building-blocks/{buildingBlockId}/mockups:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks~1{buildingBlockId}~1mockups"
  /building-blocks/{buildingBlockId}/properties:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks~1{buildingBlockId}~1properties"
  /page-building-blocks/{pageBuildingBlockId}/properties/{key}:
    $ref: "./openapi-courses.yaml#/paths/~1page-building-blocks~1{pageBuildingBlockId}~1properties~1{key}"
  /lessons/{lessonId}/teaching-units:
    $ref: "./openapi-lessons.yaml#/paths/~1lessons~1{lessonId}~1teaching-units"
  /files/{fileId}:
    $ref: "./openapi-files.yaml#/paths/~1files~1{fileId}"
  /lessons/{lessonId}/courses:
    $ref: "./openapi-courses.yaml#/paths/~1lessons~1{lessonId}~1courses"
  /building-blocks/{buildingBlockId}/properties/{key}:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks~1{buildingBlockId}~1properties~1{key}"
  /courses/{courseId}:
    $ref: "./openapi-courses.yaml#/paths/~1courses~1{courseId}"
  /teaching-phases/{teachingPhaseId}/learning-materials:
    $ref: "./openapi-lessons.yaml#/paths/~1teaching-phases~1{teachingPhaseId}~1learning-materials"
  /building-blocks:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks"
  /teaching-units/{teachingUnitId}/teaching-phases:
    $ref: "./openapi-lessons.yaml#/paths/~1teaching-units~1{teachingUnitId}~1teaching-phases"
  /discussions/{discussionId}:
    $ref: "./openapi-discussion.yaml#/paths/~1discussions~1{discussionId}"
  /courses:
    $ref: "./openapi-courses.yaml#/paths/~1courses"
  /pages/{pageId}/page-building-blocks:
    $ref: "./openapi-courses.yaml#/paths/~1pages~1{pageId}~1page-building-blocks"
  /page-building-blocks/{pageBuildingBlockId}:
    $ref: "./openapi-courses.yaml#/paths/~1page-building-blocks~1{pageBuildingBlockId}"
  /pages/{pageId}/mockups:
    $ref: "./openapi-courses.yaml#/paths/~1pages~1{pageId}~1mockups"
  /discussions:
    $ref: "./openapi-discussion.yaml#/paths/~1discussions"
  /page-mockups/{mockupId}:
    $ref: "./openapi-courses.yaml#/paths/~1page-mockups~1{mockupId}"
  /courses/{courseId}/structure:
    $ref: "./openapi-courses.yaml#/paths/~1courses~1{courseId}~1structure"
  /teaching-units/{teachingUnitId}/teaching-phases/order:
    $ref: "./openapi-lessons.yaml#/paths/~1teaching-units~1{teachingUnitId}~1teaching-phases~1order"
  /teaching-units/{teachingUnitId}:
    $ref: "./openapi-lessons.yaml#/paths/~1teaching-units~1{teachingUnitId}"
  /learning-materials/{learningMaterialId}:
    $ref: "./openapi-lessons.yaml#/paths/~1learning-materials~1{learningMaterialId}"
  /courses/{courseId}/pages/order:
    $ref: "./openapi-courses.yaml#/paths/~1courses~1{courseId}~1pages~1order"
  /comments/{commentId}:
    $ref: "./openapi-discussion.yaml#/paths/~1comments~1{commentId}"
  /building-blocks/{buildingBlockId}/release:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks~1{buildingBlockId}~1release"
  /courses/{courseId}/pages:
    $ref: "./openapi-courses.yaml#/paths/~1courses~1{courseId}~1pages"
  /lessons:
    $ref: "./openapi-lessons.yaml#/paths/~1lessons"
  /building-blocks/{buildingBlockId}/readme:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks~1{buildingBlockId}~1readme"
  /pages/{pageId}:
    $ref: "./openapi-courses.yaml#/paths/~1pages~1{pageId}"
  /pages/{pageId}/page-building-blocks/order:
    $ref: "./openapi-courses.yaml#/paths/~1pages~1{pageId}~1page-building-blocks~1order"
  /building-blocks/{buildingBlockId}:
    $ref: "./openapi-building-blocks.yaml#/paths/~1building-blocks~1{buildingBlockId}"
  /lessons/{lessonId}:
    $ref: "./openapi-lessons.yaml#/paths/~1lessons~1{lessonId}"
  /page-links/{pageId}/to/{targetPageId}:
    $ref: "./openapi-courses.yaml#/paths/~1page-links~1{pageId}~1to~1{targetPageId}"
  /page-building-blocks/{pageBuildingBlockId}/properties:
    $ref: "./openapi-courses.yaml#/paths/~1page-building-blocks~1{pageBuildingBlockId}~1properties"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
