openapi: 3.0.3
info:
  title: Building Block Repository
  description: E-Learning Specification Tool Building Blocks
  version: 1.0.0
servers:
  - url: http://localhost:8500
security:
  - bearerAuth: []
paths:
  /building-blocks:
    get:
      tags:
        - Building Block
      summary: Get all building blocks
      operationId: getBuildingBlocks
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BuildingBlock"
        401:
          description: Not Authenticated
    post:
      tags:
        - Building Block
      summary: Request new building block
      operationId: requestBuildingBlock
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBuildingBlockRequest'
        required: true
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BuildingBlockVersion"
        400:
          description: Invalid Request
        401:
          description: Not Authenticated
  /building-blocks/{buildingBlockId}/{version}:
    get:
      tags:
        - Building Block
      summary: Get building block
      operationId: getBuildingBlock
      parameters:
        - name: buildingBlockId
          in: path
          description: Id of building block
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
        - name: version
          in: path
          description: Version of building block
          required: true
          schema:
            $ref: '#/components/schemas/VersionNumber'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BuildingBlock"
        401:
          description: Not Authenticated
    patch:
      tags:
        - Building Block
      summary: Edit building block
      operationId: editBuildingBlock
      parameters:
        - name: buildingBlockId
          in: path
          description: Id of building block
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
        - name: version
          in: path
          description: Version of building block
          required: true
          schema:
            $ref: '#/components/schemas/VersionNumber'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditBuildingBlockRequest'
        required: true
      responses:
        200:
          description: Ok
        400:
          description: Invalid Request
        401:
          description: Not Authenticated
components:
  schemas:
    BuildingBlock:
      type: object
      required:
        - version
        - name
        - releaseStatus
      properties:
        version:
          $ref: "#/components/schemas/BuildingBlockVersion"
        name:
          type: string
          example: Text
        description:
          type: string
          example: Eine Komponente zum Darstellen eines Textes.
        releaseStatus:
          $ref: "#/components/schemas/ReleaseStatus"
    RequestBuildingBlockRequest:
      type: object
      required:
        - name
      properties:
        previousVersion:
          $ref: "#/components/schemas/BuildingBlockVersion"
        name:
          type: string
          example: Text
        description:
          type: string
          example: Eine Komponente zum Darstellen eines Textes.
    EditBuildingBlockRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Text
        description:
          type: string
          example: Eine Komponente zum Darstellen eines Textes.
    BuildingBlockVersion:
      type: object
      required:
        - buildingBlockId
        - version
      properties:
        buildingBlockId:
          $ref: "#/components/schemas/EntityId"
        version:
          $ref: "#/components/schemas/VersionNumber"
    ReleaseStatus:
      type: string
      enum:
        - IN_DEVELOPMENT
        - RELEASED
    VersionNumber:
      type: number
      example: 1
    EntityId:
      type: string
      format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT