openapi: 3.0.3
info:
  title: Building Block Repository
  description: E-Learning Specification Tool Building Blocks
  version: 1.0.0
servers:
  - url: http://localhost:8500
security:
  - bearerAuth: []
paths:
  /building-blocks:
    get:
      tags:
        - Building Block
      summary: Get all released building blocks
      operationId: getReleasedBuildingBlocks
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReleasedBuildingBlock"
        401:
          description: Not Authenticated
    post:
      tags:
        - Building Block
      summary: Request new building block
      operationId: requestBuildingBlock
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBuildingBlockRequest'
        required: true
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BuildingBlockVersion"
        400:
          description: Invalid Request
        401:
          description: Not Authenticated
components:
  schemas:
    ReleasedBuildingBlock:
      type: object
      required:
        - id
        - version
        - name
      properties:
        id:
          $ref: "#/components/schemas/EntityId"
        version:
          $ref: "#/components/schemas/VersionNumber"
        name:
          type: string
          example: Text
        description:
          type: string
          example: Eine Komponente zum Darstellen eines Textes.
    RequestBuildingBlockRequest:
      type: object
      required:
        - name
      properties:
        previousVersion:
          $ref: "#/components/schemas/BuildingBlockVersion"
        name:
          type: string
          example: Text
        description:
          type: string
          example: Eine Komponente zum Darstellen eines Textes.
    BuildingBlockVersion:
      type: object
      required:
        - buildingBlockId
        - version
      properties:
        buildingBlockId:
          $ref: "#/components/schemas/EntityId"
        version:
          $ref: "#/components/schemas/VersionNumber"
    VersionNumber:
      type: number
      example: 1
    EntityId:
      type: string
      format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT