openapi: 3.0.3
info:
  title: Discussions
  description: E-Learning Specification Tool Courses
  version: 1.0.0
servers:
  - url: http://localhost:8500
security:
  - bearerAuth: []
paths:
  /users/{userId}:
    get:
      tags:
        - User
      summary: Get user profile
      operationId: getUserProfile
      parameters:
        - name: userId
          in: path
          description: Id of user
          schema:
            type: string
          required: true
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        400:
          description: Invalid Request
        401:
          description: Not Authenticated
    patch:
      tags:
        - User
      summary: Edit user profile
      operationId: editUserProfile
      parameters:
        - name: userId
          in: path
          description: Id of user
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditUserProfileRequest'
        required: true
      responses:
        200:
          description: Ok
        400:
          description: Invalid Request
        401:
          description: Not Authenticated
components:
  schemas:
    UserProfile:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        firstName:
          type: string
          example: Kai
        lastName:
          type: string
          example: Happe
    EditUserProfileRequest:
      type: object
      properties:
        firstName:
          type: string
          example: Kai
        lastName:
          type: string
          example: Happe
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT