openapi: 3.0.3
info:
  title: Files
  description: E-Learning Specification Tool Courses
  version: 1.0.0
servers:
  - url: http://localhost:8500
security:
  - bearerAuth: []
paths:
  /building-blocks/{buildingBlockId}/{version}/readme:
    get:
      tags:
        - File
      summary: Get building block readme
      operationId: getBuildingBlockReadMe
      parameters:
        - name: buildingBlockId
          in: path
          description: Id of building block
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
        - name: version
          in: path
          description: Version of building block
          required: true
          schema:
            $ref: '#/components/schemas/VersionNumber'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileContent"
        401:
          description: Not Authenticated
    put:
      tags:
        - File
      summary: Edit building block readme
      operationId: editBuildingBlockReadMe
      parameters:
        - name: buildingBlockId
          in: path
          description: Id of building block
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
        - name: version
          in: path
          description: Version of building block
          required: true
          schema:
            $ref: '#/components/schemas/VersionNumber'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditFileContentRequest'
        required: true
      responses:
        200:
          description: Ok
        400:
          description: Invalid Request
        401:
          description: Not Authenticated
components:
  schemas:
    FileContent:
      type: string
      example: Inhalt einer Datei
    EditFileContentRequest:
      type: object
      required:
        - content
      properties:
        content:
          $ref: "#/components/schemas/FileContent"
    BuildingBlockVersion:
      type: object
      required:
        - buildingBlockId
        - version
      properties:
        buildingBlockId:
          $ref: "#/components/schemas/EntityId"
        version:
          $ref: "#/components/schemas/VersionNumber"
    VersionNumber:
      type: number
      example: 1
    EntityId:
      type: string
      format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT