openapi: 3.0.3
info:
  title: Files
  description: E-Learning Specification Tool Courses
  version: 1.0.0
servers:
  - url: http://localhost:8500
security:
  - bearerAuth: []
paths:
  /files/{fileId}:
    get:
      tags:
        - File
      summary: Download file
      operationId: downloadFile
      parameters:
        - name: fileId
          in: path
          description: Id of file
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
      responses:
        200:
          description: ok
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ByteArray'
        401:
          description: Not Authenticated
components:
  schemas:
    ByteArray:
      type: string
      format: byte
    EntityId:
      type: string
      format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT